spring:
  profiles.active: production

---

endpoints:
  info:
    enabled: true
    sensitive: false

  health:
    sensitive: false
    
  metrics:
    sensitive: false

server:
    port:     8090

spring:
    profiles: production
    application:
        name: spring-boot-city-paths 

citiesPathConfiguration:
     # 2 choices: DIJKSTRA, FORD 
     strategy: DIJKSTRA
     #     citiesServiceUrl: http://localhost:8080/cities
     citiesServiceUrl: http://cities-management:8080/cities
     
eureka:
    client:
        serviceUrl:
            defaultZone:    http://localhost:8761/eureka
        healthcheck:
            enabled: true
        instance:
            leaseRenewalIntervalInSeconds: 15
            preferIpAddress:  true
     