spring:
  profiles.active: production

---

endpoints:
  info:
    enabled: true
    sensitive: false

  health:
    sensitive: false
    
  metrics:
    sensitive: false

server:
    port:     8080

spring:
    profiles: production
    application:
        name: spring-boot-city-management 
    datasource:
        platform: h2
        driverClassName: org.h2.Driver
        url: jdbc:h2:mem:test;MODE=PostgreSQL  
    h2:
        console:
          enabled: true      

citiesManagementConfiguration:
     database:
        server:
           port:     9090 
           host:     localhost 
     
 
     #Secure delete endpoint
     #enableSecurity     : true    

#eureka:
#    client:
#        serviceUrl:
#            defaultZone:    http://localhost:8761/eureka
#        healthcheck:
#            enabled: true
#        instance:
#            leaseRenewalIntervalInSeconds: 15
#            preferIpAddress:  true
     